// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;

public partial class _adminDefault {

    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    private HtmlForm _form1;

    protected virtual HtmlForm form1 {
        [MethodImpl(MethodImplOptions.Synchronized)]
        get {
            return _form1;
        }

        [MethodImpl(MethodImplOptions.Synchronized)]
        set {
            _form1 = value;
        }
    }
}